Repository Cubyx-Network/website, pull requests merged in 2023-11, with the labels that each got.

#172 fix: Fehler von der Discord API werden nun abgefangen
  src/lib/server/discord.ts
  src/lib/server/teamMembers.ts
Labels: bug, hotfix, !p:high

#170 chore(main): release 0.1.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#181 feat: Weiterleitungshinweis im Header
  src/components/Header/Header.svelte
  src/components/Header/HeaderLink.svelte
  src/components/Header/HeaderMobile.svelte
  src/routes/+layout.svelte
Labels: feature

#171 content: Überarbeitung der Timeline auf der Startseite
  src/components/Timeline/AboutTimeline.svelte
  src/components/Timeline/Timeline.svelte
  src/components/Timeline/TimelineItem.svelte
Labels: content, !p:low

#156 Feat: SEO implementieren
  src/app.html
  src/components/Common/Seo.svelte
  src/lib/titleGenerator.ts
  src/routes/+error.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/datenschutz/+page.svelte
  src/routes/impressum/+page.svelte
  src/routes/team/+page.svelte
Labels: feature

#182 feat: Weiterleitungshinweise im Footer hinzugefügt
  src/components/Footer/FooterLegal.svelte
Labels: feature

#180 chore(main): release 0.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#197 chore: Imports im FooterSocialIcon verbessert
  src/components/Footer/FooterSocialIcon.svelte
Labels: change/chore

#188 chore(main): release 0.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
